server:
  port: 9001
spring:
  application:
    name: news-admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cl_news?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 12345
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  type-aliases-package: com.news.admin.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml